---
title: "Growth_Data_Exploration"
output: html_document
date: "2026-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
#library(gtools) #testing #unneeded

```

## Data

Each data pathway is different, so upload the data from your computer 

```{r}
#View(ToxGrowth)
```

```{r}
unique(ToxGrowth$Species)
```

```{r}
ToxGrowth %>%
  filter(Species == "Lampsilis siliquoidea") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 

# above species tested twice (two different years)

ToxGrowth %>%
  filter(Species == "Villosa iris") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 

ToxGrowth %>%
  filter(Species == "Hyalella azteca") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 

ToxGrowth %>%
  filter(Species == "Pimephales promelas") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 

ToxGrowth %>%
  filter(Species == "Oncorhynchus mykiss") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 

# above species tested twice (two different years)

ToxGrowth %>%
  filter(Species == "Chironomus dilutus") %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc, y = Dry_rep_wt), ) +
  geom_point(alpha=.6) 


```

```{r}
ToxGrowth$Tox_conc=as.character(ToxGrowth$Tox_conc)
ToxGrowth$Tox_conc=as.numeric(ToxGrowth$Tox_conc)
class(ToxGrowth$Tox_conc2)
ToxGrowth$Tox_conc1=str_sort(ToxGrowth$Tox_conc, numeric = TRUE) #pissing me off
print(ToxGrowth$Tox_conc)
print(ToxGrowth$Tox_conc1)

Rainbowmussel=ToxGrowth %>%
  filter(Species == "Villosa iris")

Rainbowmussel$Tox_conc3 = factor(Rainbowmussel$Tox_conc , levels=c(20, 228, 392, 713, 1462, 3000)) #also pissing me off # i forgot a comma

Rainbowmussel$Tox_conc2=mixedsort(Rainbowmussel$Tox_conc) #not doing what i want

Rainbowmussel %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc3, y = Dry_rep_wt), ) +
  geom_boxplot() 

boxplot(Rainbowmussel$Dry_rep_wt ~ Rainbowmussel$Tox_conc3)
```
```{r}

Fatmucket15=ToxGrowth %>%
  filter(Species == "Lampsilis siliquoidea") %>%
  filter(Year == "2015")
unique(Fatmucket15$Tox_conc)
unique(Fatmucket15$Year)
Fatmucket15$Tox_conc_fct = factor(Fatmucket15$Tox_conc, levels = c(20, 228, 392, 713, 1462, 3000))

Fatmucket16=ToxGrowth %>%
  filter(Species == "Lampsilis siliquoidea") %>%
  filter(Year == "2016")          
unique(Fatmucket16$Tox_conc)
unique(Fatmucket16$Year)
Fatmucket16$Tox_conc_fct = factor(Fatmucket16$Tox_conc, levels = c(1.5, 17.3, 34.3, 75.3, 152.3, 320.1))

Rainbowmussel=ToxGrowth %>%
  filter(Species == "Villosa iris")
unique(Rainbowmussel$Tox_conc)
Rainbowmussel$Tox_conc_fct = factor(Rainbowmussel$Tox_conc , levels=c(20, 228, 392, 713, 1462, 3000))

Scuds=ToxGrowth %>%
  filter(Species == "Hyalella azteca")
unique(Scuds$Tox_conc)
Scuds$Tox_conc_fct = factor(Scuds$Tox_conc, levels = c(54, 171, 292, 532, 1014, 1990))

Fatheadminnow=ToxGrowth %>%
  filter(Species == "Pimephales promelas")
unique(Fatheadminnow$Tox_conc)
Fatheadminnow$Tox_conc_fct = factor(Fatheadminnow$Tox_conc, levels = c(17.5, 224.3, 370.9, 765.7, 1566.9, 3032.4))

Rainbowtrout16=ToxGrowth %>%
  filter(Species == "Oncorhynchus mykiss") %>%
  filter(Year == "2016")
unique(Rainbowtrout16$Tox_conc)
unique(Rainbowtrout16$Year)
Rainbowtrout16$Tox_conc_fct = factor(Rainbowtrout16$Tox_conc, levels = c(1.5, 9.8, 20.7, 40.2, 82.0, 166.3))

Rainbowtrout18=ToxGrowth %>%
  filter(Species == "Oncorhynchus mykiss") %>%
  filter(Year == "2018")
unique(Rainbowtrout18$Tox_conc)
unique(Rainbowtrout18$Year)
Rainbowtrout18$Tox_conc_fct = factor(Rainbowtrout18$Tox_conc, levels = c(19.0, 210.3, 419.4, 781.0, 1579.9, 3240.4))

Midge=ToxGrowth %>%
  filter(Species == "Chironomus dilutus")
unique(Midge$Tox_conc)
Midge$Tox_conc_fct = factor(Midge$Tox_conc, levels = c(0.2, 5.7, 11, 21.2, 44.7, 96.6))
```

```{r}
Fatmucket15 %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Fatmucket16 %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Rainbowmussel %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 


Scuds %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Fatheadminnow %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Rainbowtrout16 %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Rainbowtrout18 %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 

Midge %>%
  replace(is.na(.), 0) %>%
  ggplot(aes(x = Tox_conc_fct, y = Dry_rep_wt), ) +
  geom_boxplot() 


```


```{r}
head(Fatmucket15)


dim(Fatmucket15)

mean(Fatmucket15$Tox_conc)
sd(Fatmucket15$Tox_conc)

mean(Fatmucket15$Survival)
sd(Fatmucket15$Survival)

fm51 = rnorm(24, mean=969.1667, sd=1039.746)
fm52 = rnorm(24, mean=8.291667, sd=3.793348)
t.test(fm51, fm52, var.equal = T)


head(Fatmucket16)

dim(Fatmucket16)

mean(Fatmucket16$Tox_conc)
sd(Fatmucket16$Tox_conc)
                                        
mean(Fatmucket16$Survival)
sd(Fatmucket16$Survival)

fhm1 = rnorm(48, mean=100.1333, sd=111.2003)
fhm2 = rnorm(48, mean=9.854167, sd=0.4607849)
t.test(fhm1, fhm2, var.equal = T)

head(Rainbowmussel)

as.numeric(Rainbowmussel$Tox_conc)
dim(Rainbowmussel)

mean(Fatheadminnow$Tox_conc)
sd(Fatheadminnow$Tox_conc)

mean(Fatheadminnow$Survival)
sd(Fatheadminnow$Survival)

rbm1 = rnorm(24, mean=996.2833, sd=1060.732)
rbm2 = rnorm(24, mean=10.70833, sd=5.376917)
t.test(rbm1, rbm2, var.equal = T)


head(Scuds)


dim(Scuds)

mean(Scuds$Tox_conc)       
sd(Scuds$Tox_conc)

mean(Scuds$Survival)
sd(Scuds$Survival)

scd1 = rnorm(30, mean=675.5, sd=676.061)
scd2 = rnorm(30, mean=9.6, sd=0.8550055)
t.test(scd1, scd2, var.equal = T)


head(Fatheadminnow)

dim(Fatheadminnow)

mean(Fatheadminnow$Tox_conc)
sd(Fatheadminnow$Tox_conc)

mean(Fatheadminnow$Survival)
sd(Fatheadminnow$Survival)

fhm1 = rnorm(24, mean=996.2833, sd=1060.732)
fhm2 = rnorm(24, mean=10.70833, sd=5.376917)
t.test(fhm1, fhm2, var.equal = T)


head(Rainbowtrout16)

dim(Rainbowtrout16)

mean(Rainbowtrout16$Tox_conc)
sd(Rainbowtrout16$Tox_conc)

mean(Rainbowtrout16$Survival)
sd(Rainbowtrout16$Survival)

rt61 = rnorm(24, mean=53.41667, sd=58.08909)
rt62 = rnorm(24, mean=10, sd=0)
t.test(rt61, rt62, var.equal = T)


head(Rainbowtrout18)

dim(Rainbowtrout18)

mean(Rainbowtrout18$Tox_conc)
sd(Rainbowtrout18$Tox_conc)

mean(Rainbowtrout18$Survival)
sd(Rainbowtrout18$Survival)

rt81 = rnorm(24, mean=1041.667, sd=1128.007)
rt82 = rnorm(24, mean=13.29167, sd=1.428869)
t.test(fhm1, fhm2, var.equal = T)


head(Midge)

dim(Midge)

mean(Midge$Tox_conc)
sd(Midge$Tox_conc)

mean(Midge$Survival)
sd(Midge$Survival)

mdg1 = rnorm(48, mean=29.9, sd=33.4373)
mdg2 = rnorm(48, mean=9.208333, sd=1.486941)
t.test(mdg1, mdg2, var.equal = T)

```


```{r}
ds1 = ToxGrowth %>%
  group_by(Species, factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked))) %>%
  arrange(desc(Species))

ds1 %>% 
  case_when(Species == "")

Midge %>%
  ggplot(aes(x=factor(Tox_conc), y=percent_survival)) +
    geom_bar(stat = "identity") +
  facet_wrap(~Species, scales = "free_x")

Fatmucket15=ToxGrowth %>%
  filter(Species == "Lampsilis siliquoidea") %>%
  filter(Year == "2015") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Fatmucket16=ToxGrowth %>%
  filter(Species == "Lampsilis siliquoidea") %>%
  filter(Year == "2016") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Rainbowmussel=ToxGrowth %>%
  filter(Species == "Villosa iris") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Scuds=ToxGrowth %>%
  filter(Species == "Hyalella azteca") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Fatheadminnow=ToxGrowth %>%
  filter(Species == "Pimephales promelas") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Rainbowtrout16=ToxGrowth %>%
  filter(Species == "Oncorhynchus mykiss") %>%
  filter(Year == "2016") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Rainbowtrout18=ToxGrowth %>%
  filter(Species == "Oncorhynchus mykiss") %>%
  filter(Year == "2018") %>% 
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))

Midge=ToxGrowth %>%
  filter(Species == "Chironomus dilutus") %>%
  group_by(factor(Tox_conc)) %>%
  mutate(percent_survival = 1-(sum(Survival)/sum(Stocked)))
```

```{r}
Fatmucket15 %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Fatmucket 2015 Experiment",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Fatmucket16 %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent)  +
  labs(title = "Fatmucket 2016 Experiment",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Rainbowmussel %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Rainbow Mussel",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Scuds %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Scuds",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Fatheadminnow %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Fathead Minnow",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Rainbowtrout16 %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Rainbow Trout 2016 Experiment",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Rainbowtrout18 %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Rainbow Trout 2018 Experiment",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()

Midge %>%
  distinct(Tox_conc, percent_survival) %>%
  select(`factor(Tox_conc)`, percent_survival) %>%
  ggplot(aes(x = `factor(Tox_conc)`, y = percent_survival)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent)  +
  labs(title = "Midge",
       x= "Concentration of Toxicant",
       y= "Percent of Organisms that Survived") +
  theme_minimal()
```





