---
title: "survival_exploration"
output: html_document
---

```{r}
library(tidyverse)

survival = read_csv("C:/Users/ema4p/Downloads/ENVSDATA_data - Survival of test organisms in exposeure bioessay.csv")
```

```{r}
survival = survival %>%
  mutate(survival_rate = Survival/Stocked)

print(unique(survival$Toxicant))
```

```{r}
#relationship between concentration of the two toxicants and survival rate

survival %>%
  filter(Toxicant == "Sulfate") %>%
  ggplot(aes(x = Tox_conc, y = survival_rate)) +
    geom_point() +
    geom_smooth(color = "deepskyblue3") +
    labs(title = "Survival Rate vs Sulfate Concentration", x = "Sulfate Concentration", y = "Survival Rate") +
  theme_bw()

survival %>%
  filter(Toxicant == "Nitrate") %>%
  filter(Tox_conc < 2500) %>%
  ggplot(aes(x = Tox_conc, y = survival_rate)) +
    geom_point() +
    geom_smooth(color = "deepskyblue3") +
    labs(title = "Survival Rate vs Nitrate Concentration",x = "Nitrate Concentration", y = "Survival Rate") +
  theme_bw()

#There's an outlier in the Nitrate Concentration that's messing with the regression line, COULD cut it out of the data set or just from the graph unless we feel a need to keep it
```

```{r}
#seeing how each species did with Sulfate
names <- c("Hyalella azteca" = "Sideswimmers", "Lampsilis siliquoidea" = "Fatmucket", "Oncorhynkiss mykiss" = "Rainbow Trout", "Pimephales promelas" = "Fathead Minnow", "Villosa iris" = "Rainbow Mussel")

survival %>%
  filter(Toxicant == "Sulfate") %>%
  ggplot(aes(x = Tox_conc, y = survival_rate)) +
  geom_point() +
  geom_smooth(color = "deepskyblue3") +
    labs(title = "Species Survival Rate vs Sulfate Concentration",x = "Sulfate Concentration", y = "Survival Rate") +
  facet_wrap(~Species, labeller = as_labeller(names)) +
  theme_bw()
```

```{r}
#seeing how each species did with Nitrate
names2 <- c("Lampsilis siliquoidea" = "Fatmucket", "Hyla versicolor" = "Gray Treefrog", "Chironomus dilutus" = "Midge", "Lithobates sylvaticus" = "Wood Frog", "Oncorhynchus mykiss" = "Rainbow Trout")

survival %>%
  filter(Toxicant == "Nitrate") %>%
  ggplot(aes(x = Tox_conc, y = survival_rate)) +
  geom_point() +
  geom_smooth(color = "deepskyblue3") +
  labs(title = "Species Survival Rate vs Nitrate Concentration",x = "Nitrate Concentration", y = "Survival Rate") +
  facet_wrap(~Species, labeller = as_labeller(names2)) +
  theme_bw()
```

```{r}
#The concentration, survival and growth data sets all have Days 34, 42 and 55

print(unique(concentration$Day))

print(unique(survival$Day))

print(unique(growth$Day))

print(unique(concentration_chronic$Day))

```


```{r}
#Hyalella Azteca is observed 4 vs 42, Lampsilis is 4 vs 28, Oncorhynkiss is only 55,
#Pimephales is 7 vs 34, and Villosa iris is 4 vs 28

#starting days are 4 and 7, ending days are 28 and 34

survival %>%
  mutate(Day = as.factor(Day)) %>%
  filter(Toxicant == "Sulfate") %>%
  ggplot(aes(x = Day, y = survival_rate)) +
  geom_boxplot()

survival %>%
  mutate(Day = as.factor(Day)) %>%
  filter(Toxicant == "Sulfate") %>%
  ggplot(aes(x = Day, y = survival_rate)) +
  geom_boxplot() +
  facet_wrap(~Species)
```





